"use strict";
/* test_mistake_learner.js — regression for the 2026-09-07 weekly report.
 *
 * That report was generated BY the AI mistake learner, and every one of its
 * "detected mistakes" was an artefact of the learner itself:
 *
 *   `renderItinerary()` closes an itinerary with a `<--additional-->` echo
 *   block ("1 AA 6935Q 12OCT"). The learner's row filter matched those lines,
 *   so a 4-leg trip reported "direct found 12, AI found 8", and rows were
 *   compared by position — index 3 of one itinerary against index 3 of a
 *   differently-segmented other itinerary. Each mis-pairing taught a rule like
 *   `AA 6935Q -> AA 6618O` (not a glyph confusion at all: those are two
 *   different flights), and the *reverse* rule was taught in the same pass, so
 *   the rule list contradicted itself. Those rules were then applied to every
 *   conversion, including typed text, rewriting correct flight numbers.
 *
 * Everything here runs the REAL app.js learner and the REAL app.js cleaner, so
 * the assertions cover the path a browser takes, not a re-implementation.
 */
const fs = require("fs");
const path = require("path");
const vm = require("vm");

const REPO = __dirname;
const E = require(path.join(REPO, "spicy_engine.js"));
const APP = fs.readFileSync(path.join(REPO, "app.js"), "utf8");

let PASS = 0, FAIL = 0;
function assert(cond, msg) {
  if (cond) { PASS++; console.log("PASS:", msg); }
  else { FAIL++; console.error("FAIL:", msg); }
}
function section(t) { console.log("\n=== " + t + " ==="); }

/* ---------- storage-backed sandbox for the real learner ---------- */
function makeStore(seedRules) {
  const data = Object.create(null);
  if (seedRules) data.spicy_learned_rules_v1 = JSON.stringify(seedRules);
  return {
    data,
    getItem: (k) => (k in data ? data[k] : null),
    setItem: (k, v) => { data[k] = String(v); },
    rules: () => JSON.parse(data.spicy_learned_rules_v1 || "[]"),
    mistakes: () => JSON.parse(data.spicy_mistakes_log_v1 || "[]")
  };
}

function loadLearner(store) {
  const start = APP.indexOf("/* LEARNER:BEGIN */");
  const end = APP.indexOf("/* LEARNER:END */");
  if (start < 0 || end < 0) throw new Error("learner markers not found in app.js");
  const sandbox = {
    console,
    Date,
    JSON,
    RegExp,
    String,
    Number,
    Math,
    Object,
    Array,
    document: { createElement: () => ({ textContent: "", innerHTML: "" }) },
    localStorage: { getItem: store.getItem, setItem: store.setItem },
    loadStats: () => ({ week: new Date().toISOString().slice(0, 10),
                        period: { total: 65, textDirect: 64, imgDirect: 1, aiResolved: 0, aiCalls: 7, durations: [347] },
                        lifetime: { total: 65, textDirect: 64, imgDirect: 1, aiResolved: 0, aiCalls: 7 },
                        history: [] }),
    window: {}
  };
  sandbox.window = sandbox;
  vm.createContext(sandbox);
  vm.runInContext(APP.slice(start, end), sandbox, { filename: "learner.js" });
  vm.runInContext(
    "this.__api = { teachRule: teachRule, detectMistakesAndLearn: detectMistakesAndLearn," +
    " flightRowsOf: flightRowsOf, isPlausibleGlyphConfusion: isPlausibleGlyphConfusion," +
    " clockCore: clockCore, loadLearnedRules: loadLearnedRules, pruneLearnedRules: pruneLearnedRules," +
    " loadMistakes: loadMistakes };",
    sandbox);
  return sandbox.__api;
}

/* ---------- the real cleanOcrText, with a rule store we control ---------- */
function loadCleaner(rules) {
  const start = APP.indexOf("var _cleanAirlines = []");
  const end = APP.indexOf("/* ---------- bounded, non-blocking screenshot OCR ---------- */");
  if (start < 0 || end < 0) throw new Error("cleaner markers not found in app.js");
  const sandbox = {
    console,
    window: {},
    SPICY_DATA: require(path.join(REPO, "spicy_data.js")),
    document: { createElement: () => ({ textContent: "", innerHTML: "" }) },
    localStorage: { getItem: () => null, setItem: () => {} },
    loadLearnedRules: () => rules || []
  };
  sandbox.window = sandbox;
  vm.createContext(sandbox);
  vm.runInContext(APP.slice(start, end), sandbox, { filename: "cleaner.js" });
  vm.runInContext("this.__clean = cleanOcrText;", sandbox);
  return sandbox.__clean;
}

/* ================= 1. the learner must not invent rules ================= */
section("1. Self-learning rules from the 2026-09-07 report");

const LAXMAN_INPUT =
  "Los Angeles (LAX) to Manchester (MAN) on Mon, Oct 12 Warning Icon\n\n" +
  "Los Angeles (LAX) to London (LHR) on Mon, Oct 12\n3:45 PM to 10:15 AM (10h 30m)\n" +
  "American 6935 (operated by British";
const LAXMAN_DIRECT =
  "1 AA 6935 12OCT LAX LHR 345P 1015A\u00a51 Q 77W 10.30 5456 N\n" +
  "DEP-LOS ANGELES INTL\nARR-LONDON HEATHROW\nCABIN-ECONOMY\n\n" +
  "2 AA 7037 13OCT LHR MAN 1205P 110P S 320 1.05 152 N\n" +
  "DEP-LONDON HEATHROW\nARR-MANCHESTER I\nCABIN-ECONOMY\n\n" +
  "3 TO 105 22OCT MHT MAN ???? ???? \u00a51\n" +
  "4 AA 137 22OCT LHR LAX 455P 810P\u00a51\n\n<--additional-->\n1 AA 6935Q 12OCT\n2 AA 137 22OCT\n3 AA 7037S 13OCT";
const LAXMAN_AI =
  "1 AA 6935 12OCT LAX LHR 345P 1015A\u00a51 Q 77W 10.30 5456 N\n" +
  "DEP-LOS ANGELES INTL\nARR-LONDON HEATHROW\nCABIN-ECONOMY\n\n" +
  "2 AA 7037 13OCT LHR MAN 1205P 110P S 320 1.05 151 N\n" +
  "DEP-LONDON HEATHROW\nARR-MANCHESTER INTL\nCABIN-ECONOMY\n\n" +
  "3 AA 6618 22OCT MAN LHR 745A 900A O 320 1.15 151 N\n" +
  "4 AA 137 22OCT LHR LAX 455P 810P\u00a51 Q 77W 11.15 5456 N\n\n<--additional-->\n1 AA 6618O 22OCT\n2 AA 7037S 13OCT";

{
  const store = makeStore();
  const L = loadLearner(store);
  L.detectMistakesAndLearn(LAXMAN_INPUT, LAXMAN_DIRECT, LAXMAN_AI, "departure time missing");
  const rules = store.rules();
  assert(rules.length === 0,
    "no rule taught from mis-paired legs (got " + rules.length + ": " +
    rules.map(r => r.pattern + "->" + r.replacement).join(", ") + ")");
  assert(!rules.some(r => /^AA (6935Q|137|7037S|6618)$/.test(r.pattern)),
    "the four contradictory AA rules from the report are not re-created");
  const mistakes = store.mistakes();
  assert(mistakes.length === 1, "the discrepancy itself is still logged (" + mistakes.length + " entry)");
  assert(/not learned|no matching AI leg|refused|ambiguous/i.test(mistakes[0].summary),
    "the log says *why* nothing was learned: " + JSON.stringify(mistakes[0].summary).slice(0, 150));
  assert(!/1\.05 152 vs 1\.05 151/.test(mistakes[0].summary), "distance jitter is not reported as a mistake");
}

section("2. the echo block is not a flight");
{
  const store = makeStore();
  const L = loadLearner(store);
  const rows = L.flightRowsOf(LAXMAN_DIRECT);
  assert(rows.length === 4, "4 itinerary rows read, `<--additional-->` echo excluded (got " + rows.length + ")");
  assert(!rows.some(r => r.raw.indexOf("additional") >= 0), "no echo line counted as a segment");
  const full = E.renderItinerary(E.parse(LAXMAN_DIRECT)[0]);
  assert(L.flightRowsOf(full).every(r => !/^1 AA 6935Q/.test(r.raw) || r.raw.indexOf("additional") < 0),
    "echo lines never carry a route field that reads as an airport pair");
}

section("3. times are compared without their day-shift marker");
{
  const store = makeStore();
  const L = loadLearner(store);
  assert(L.clockCore("810P\u00a51") === "810P" && L.clockCore("810P+1") === "810P" && L.clockCore("745A") === "745A",
    "810P¥1 / 810P+1 / 745A normalise to their clock");
  const direct =
    "1 AA 6935 12OCT LAX LHR 345P 1015A\u00a51 Q 77W 10.30 5456 N\n" +
    "2 AA 137 22OCT LHR LAX 455P 810P\u00a51 Q 77W 11.15 5456 N";
  const ai =
    "1 AA 6935 12OCT LAX LHR 345P 1015A\u00a51 Q 77W 10.30 5456 N\n" +
    "2 AA 137 22OCT LHR LAX 455P 810P\u00a51 Q 77W 11.15 5456 N";
  L.detectMistakesAndLearn("American 6935 ... American 137", direct, ai, "AI correction");
  assert(store.mistakes().length === 0, "identical itineraries differing only in the ¥1 marker log nothing");
}

section("4. a real glyph confusion is still learned");
{
  const store = makeStore();
  const L = loadLearner(store);
  const src = "1 OZ   501 12OCT ICN JFK 100A 900A Y 77W 14.00 6000 N";
  const direct = "1 OZ 50I 12OCT ICN JFK 100A 900A Y 77W 14.00 6000 N";
  L.detectMistakesAndLearn(src, direct, src, "AI correction");
  const rules = store.rules();
  assert(rules.length === 1, "one rule taught (got " + rules.length + ")");
  assert(rules[0] && rules[0].pattern === "OZ 50I" && rules[0].replacement === "OZ 501",
    "rule is the look-alike fix: " + (rules[0] ? rules[0].pattern + " -> " + rules[0].replacement : "n/a"));
  assert(rules[0] && rules[0].type === "flight_num" && rules[0].evidence === 1,
    "rule carries its provenance (type + evidence count)");
  L.detectMistakesAndLearn(src, direct, src, "AI correction");
  assert(store.rules()[0].evidence === 2, "seeing the same misread twice strengthens the rule instead of duplicating it");

  assert(L.isPlausibleGlyphConfusion("AA 137", "AA 7037S") === false, "AA 137 -> AA 7037S is not a glyph confusion");
  assert(L.isPlausibleGlyphConfusion("AV 126", "AV 127") === false, "AV 126 -> AV 127 is a different flight, not a glyph");
  assert(L.isPlausibleGlyphConfusion("AT 800C", "AT 800O") === true, "AT 800C -> AT 800O (C/0) is a scanner confusion");
  assert(L.teachRule({ type: "flight_num", pattern: "AA 137", replacement: "AA 7037S", why: "x" }) ===
    "rejected: not a glyph confusion", "teachRule refuses a non-glyph rule outright");
}

section("5. contradictory (reversed) rules cancel instead of accumulating");
{
  // A real look-alike pair (SO5 <-> 505), taught in both directions by the old
  // position-based learner: whichever row it saw first became "the truth".
  const store = makeStore([
    { type: "flight_num", pattern: "OZ SO5", replacement: "OZ 505", why: "old", evidence: 1 }
  ]);
  const L = loadLearner(store);
  const res = L.teachRule({ type: "flight_num", pattern: "OZ 505", replacement: "OZ SO5",
    why: "AI corrected flight number glyph error", evidence: 1 });
  assert(res === "rejected: reversed pair", "the reverse of an existing rule is rejected (" + res + ")");
  assert(store.rules().length === 0, "and the original cancelled rule is dropped, so neither can fire");
}

/* ================= 6. learned rules never touch typed text ================= */
section("6. rules rewrite screenshot OCR only, never a paste");
{
  const rules = [
    { type: "flight_num", pattern: "AA 137", replacement: "AA 7037S", why: "test", evidence: 2 },
    { type: "flight_num", pattern: "AV 126", replacement: "AV 127", why: "test", evidence: 2 }
  ];
  const clean = loadCleaner(rules);
  const typed = "1 AV 126 14SEP BOG MIA 735A 1225P F 320 3.50 1506 N";
  assert(clean(typed, { learned: false }).indexOf("AV 126") >= 0,
    "paste path: AV 126 survives (a typed itinerary is ground truth)");
  assert(clean(typed).indexOf("AV 127") >= 0,
    "OCR path: the same rule still repairs a screenshot");
  assert(clean("American 137 departs 4:55 PM", { learned: false }).indexOf("137") >= 0,
    "paste path: 'American 137' is never rewritten to another flight");
}

/* ================= 7. the GDS re-paste that needed no AI at all ================= */
section("7. GDS re-pastes parse offline (the case that produced the phantom TK 2)");
{
  const clean = loadCleaner([]);
  const REPOST =
    " 1 OB 765Z 15SEP T MIAVVI HK2  1010A  500P /DCOB*AKI38S /E\n" +
    " 2 OB 708S 16SEP W VVIEZE TK2  1000A  155P /DCOB*AKI38S /E\n" +
    " 3 OB 701S 20NOV F EZEVVI TK2   250A  445A /DCOB*AKI38S /E\n" +
    " 4 ";
  const cleaned = clean(REPOST);
  assert(/\b15SEP\b/.test(cleaned) && /\b20NOV\b/.test(cleaned),
    "the cleaner no longer splits a GDS date into `15 SEP`");
  const [segs, warns] = E.parse(cleaned);
  assert(segs.length === 3, "3 legs read offline (got " + segs.length + ")");
  assert(!segs.some(s => s.airline === "TK"), "no phantom `TK 2` leg invented from the sell-status column");
  const ids = segs.map(s => s.airline + " " + s.flight_no + " " + s.date_ddmmm + " " + s.orig + "-" + s.dest + " " + s.dep_time + "/" + s.arr_time);
  assert(ids.join(" | ") ===
    "OB 765 15SEP MIA-VVI 1010A/500P | OB 708 16SEP VVI-EZE 1000A/155P | OB 701 20NOV EZE-VVI 250A/445A",
    "each leg keeps its own date, route and clocks: " + ids.join(" | "));
  assert(!warns.some(w => /NOT read/i.test(w)), "no row is silently dropped: " + JSON.stringify(warns));
}

section("8. a duration column is not a clock, and a date is not an airport");
{
  const clean = loadCleaner([]);
  const gds = "1 EY   85 04SEP AUH FCO  330A  740A   D    77W  6.10  2699  N";
  assert(/ 6\.10 /.test(clean(gds)), "77W 6.10 2699 keeps its flight-time column (no 6:10 rewrite)");
  const [segs] = E.parse(clean(gds));
  assert(segs.length === 1 && segs[0].flight_time === "6.10",
    "duration survives the round trip (got " + (segs[0] && segs[0].flight_time) + ")");
  assert(segs[0].aircraft === "77W" && segs[0].distance === "2699",
    "aircraft and mileage stay in their own columns");
  const prose = "New York (JFK) to Copenhagen (CPH) on Wed, Aug 26";
  assert(/AUG 26/.test(clean(prose)), "prose dates are still uppercased and spaced: " + JSON.stringify(clean(prose)));
}

section("9. weekly report explains itself");
{
  const start = APP.indexOf("/* REPORT:BEGIN */");
  const end = APP.indexOf("/* REPORT:END */");
  if (start < 0 || end < 0) throw new Error("report markers not found in app.js");
  const store = makeStore([{ type: "flight_num", pattern: "OZ 50I", replacement: "OZ 501",
    why: "AI corrected flight number glyph error", evidence: 2, seen: "2026-09-03" }]);
  const L = loadLearner(store);
  L.detectMistakesAndLearn(LAXMAN_INPUT, LAXMAN_DIRECT, LAXMAN_AI, "departure time missing");
  const email = (APP.match(/var AUTHOR_EMAIL = "([^"]+)"/) || [])[1];
  assert(!!email, "weekly report still targets the address configured in app.js");
  const sandbox = {
    console, Date, JSON, String, Number, Math, Object, Array, RegExp,
    AUTHOR_EMAIL: email,
    localStorage: { getItem: store.getItem, setItem: store.setItem },
    navigator: { userAgent: "ArenaTestAgent" },
    window: {}
  };
  sandbox.window = sandbox;
  // The real loadStats returns a week window, not flat lifetime counters; the
  // stub mirrors that shape so the report under test sees what production sees.
  const _d = new Date(), _shift = (_d.getUTCDay() + 6) % 7;
  const weekStart = new Date(Date.UTC(_d.getUTCFullYear(), _d.getUTCMonth(), _d.getUTCDate() - _shift))
    .toISOString().slice(0, 10);
  const counters = { total: 65, textDirect: 64, imgDirect: 1, aiResolved: 3, aiCalls: 7, durations: [347] };
  sandbox.loadStats = () => ({
    week: weekStart,
    period: Object.assign({}, counters),
    lifetime: Object.assign({}, counters),
    history: [{ week: "2026-08-31", total: 12, textDirect: 11, imgDirect: 0, aiResolved: 1, aiCalls: 2 }]
  });
  sandbox.aiModelGet = () => "gemini-3.7-flash";
  vm.createContext(sandbox);
  vm.runInContext("var navigator = { userAgent: 'ArenaTestAgent' };", sandbox);
  vm.runInContext(APP.slice(APP.indexOf("/* LEARNER:STATS */") + "/* LEARNER:STATS */".length, start), sandbox, { filename: "stats.js" });
  vm.runInContext(APP.slice(start, end), sandbox, { filename: "report.js" });
  vm.runInContext("this.__report = generateWeeklyReportText;", sandbox);
  const report = sandbox.__report();
  assert(/ACTIVE SELF-LEARNED RULES \(1\)/.test(report), "report counts the active rules");
  assert(/OCR text only; seen 2x, since 2026-09-03/.test(report),
    "each rule states its scope and evidence: " + (report.match(/#1 \[flight_num\].*/) || ["(missing)"])[0]);
  assert(/applied to screenshot OCR only/.test(report), "report states rules never rewrite a paste");
  assert(/CORRECTIONS THE LEARNER REFUSED/.test(report), "report separates refused corrections from learned ones");
  assert(/comparison artefacts/.test(report), "recommendations explain why nothing was learned");
  assert(!/DEP-\?\?\?|12, AI found 8/.test(report.split("--- 4.")[0].replace(/Direct:/g, "")) ||
         /paired by flight identity/.test(report), "count discrepancy is reported as identity-paired");
}

section("10. a store polluted by the old learner heals itself once");
{
  // The exact 14 rules from the 2026-09-07 report, plus one legitimate fix.
  const LEGACY = [
    { type: "flight_num", pattern: "AA 7037S", replacement: "AA 137B", why: "AI corrected flight number glyph error" },
    { type: "flight_num", pattern: "AA 6935Q", replacement: "AA 6618O", why: "AI corrected flight number glyph error" },
    { type: "flight_num", pattern: "AA 137", replacement: "AA 7037S", why: "AI corrected flight number glyph error" },
    { type: "flight_num", pattern: "AA 6618", replacement: "AA 137", why: "AI corrected flight number glyph error" },
    { type: "flight_num", pattern: "AV 127F", replacement: "AV 126F", why: "AI corrected flight number glyph error" },
    { type: "flight_num", pattern: "AV 126F", replacement: "AV 127F", why: "AI corrected flight number glyph error" },
    { type: "flight_num", pattern: "AV 127", replacement: "AV 126", why: "AI corrected flight number glyph error" },
    { type: "flight_num", pattern: "AV 126", replacement: "AV 127", why: "AI corrected flight number glyph error" },
    { type: "flight_num", pattern: "AT 800C", replacement: "AT 250D", why: "AI corrected flight number glyph error" },
    { type: "flight_num", pattern: "AT 251C", replacement: "AT 765D", why: "AI corrected flight number glyph error" },
    { type: "flight_num", pattern: "OZ 50I", replacement: "OZ 501", why: "AI corrected flight number glyph error", evidence: 1 }
  ];
  const store = makeStore(LEGACY);
  const L = loadLearner(store);
  const kept = L.loadLearnedRules();
  assert(kept.length === 1, "the report's 10 bogus rules are swept, the 1 real glyph fix stays (kept " + kept.length + ")");
  assert(kept[0] && kept[0].pattern === "OZ 50I", "the surviving rule is the look-alike fix: " + JSON.stringify(kept[0] && kept[0].pattern));
  assert(JSON.parse(store.data.spicy_learned_rules_v1).length === 1, "the sweep is persisted, not just filtered in memory");
  assert(L.loadLearnedRules().length === 1, "a second load is a no-op (the store is marked as swept)");
  const store2 = makeStore(LEGACY);
  const L2 = loadLearner(store2);
  const swept = L2.pruneLearnedRules(LEGACY);
  assert(swept.every(r => L2.isPlausibleGlyphConfusion(r.pattern, r.replacement)),
    "every surviving rule is a real glyph confusion");
  assert(!swept.some(r => r.pattern === "AV 127" || r.replacement === "AV 127" || r.pattern === "AV 126" || r.replacement === "AV 126"),
    "the AV 126/AV 127 reversal pair is gone in both directions");
}

section("11. the repaired cleaner is idempotent on a GDS table");
{
  const clean = loadCleaner([]);
  const REPOST =
    " 1 OB 765Z 15SEP T MIAVVI HK2  1010A  500P /DCOB*AKI38S /E\n" +
    " 2 OB 708S 16SEP W VVIEZE TK2  1000A  155P /DCOB*AKI38S /E\n" +
    " 3 OB 701S 20NOV F EZEVVI TK2   250A  445A /DCOB*AKI38S /E\n 4 ";
  const once = clean(REPOST);
  const twice = clean(once);
  assert(once.replace(/\s+/g, " ") === twice.replace(/\s+/g, " "),
    "cleaning an already-clean GDS table changes nothing (a re-paste cannot drift)");
  const [segs] = E.parse(clean(once));
  assert(segs.length === 3, "and it still parses to 3 legs after a second pass (got " + segs.length + ")");
}

section("12. a card list's time-only line belongs to the leg BELOW it");
{
  // Report case #1/#5 shape: `3:45 PM to 10:15 AM` printed above the flight
  // number. The previous leg's window had already eaten that line, so leg 1 got
  // the right clocks and every leg after it printed `????` — or, when the card
  // had no blank line at all, the previous leg's clocks.
  const CARDS =
    "Los Angeles (LAX) to London (LHR) on Mon, Oct 12\n" +
    "3:45 PM to 10:15 AM (10h 30m)\nAmerican 6935 (operated by British Airways)\n\n" +
    "London (LHR) to Manchester (MAN) on Tue, Oct 13\n" +
    "12:05 PM to 1:10 PM (1h 5m)\nAmerican 7037 (operated by British Airways)\n\n" +
    "Manchester (MAN) to London (LHR) on Mon, Oct 22\n" +
    "7:45 AM to 9:00 AM (1h 15m)\nAmerican 6618\n\n" +
    "London (LHR) to Los Angeles (LAX) on Mon, Oct 22\n" +
    "4:55 PM to 8:10 PM (11h 15m)\nAmerican 137";
  const clean = loadCleaner([]);
  const [segs, warns] = E.parse(clean(CARDS));
  assert(segs.length === 4, "4 legs read from the card list (got " + segs.length + ")");
  const clocks = segs.map(s => s.airline + " " + s.flight_no + " " + s.dep_time + "/" + s.arr_time);
  assert(clocks.join(" | ") === "AA 6935 345P/1015A | AA 7037 1205P/110P | AA 6618 745A/900A | AA 137 455P/810P",
    "every leg keeps its own pair of clocks: " + clocks.join(" | "));
  assert(!/\?\?\?\?/.test(E.renderItinerary(segs)), "no ???? clock anywhere in the itinerary");
  assert(!warns.some(w => /missing -> \?\?\?\?/.test(w)),
    "and no 'time missing' warning: " + JSON.stringify(warns));

  // The borrow must stay a *whole* standalone line: the tail of the previous
  // leg's own line is that leg's data and must never be handed to the next one.
  const TWO_LINES =
    "British Airways 1543 31 Aug Chicago (ORD) 6:15 PM London Heathrow (LHR) 8:05 AM +1 Business Boeing 787-8\n" +
    "British Airways 396 1 Sep London Heathrow (LHR) 10:10 AM Cairo (CAI) 5:20 PM Business A321neo";
  const [two] = E.parse(TWO_LINES);
  assert(two.length === 2 && two[0].dep_time === "615P" && two[1].dep_time === "1010A" &&
         two[1].date_ddmmm === "01SEP",
    "a leg never inherits the previous line's date or clocks (" +
    two.map(x => x.flight_no + " " + x.date_ddmmm + " " + x.dep_time).join(", ") + ")");
}

console.log(`\n=== SUMMARY: ${PASS} passed, ${FAIL} failed ===`);
if (FAIL > 0) process.exit(1);
